version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 21 e npm...      
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
      - npm install --loglevel=error
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Create Database
      - npx sequelize db:create 2>/dev/null
      - echo Migrate Database
      - npx sequelize db:migrate 2>/dev/null
      - echo Build finalizado em `date`
