version: 0.2

env:
  variables:
    REACT_APP_API_URL: "http://localhost:3001"

phases:
  install:
    commands:
      - echo Installing Node 21 e npm...      
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Compiling the Node.js code
      - ls -lha
      - npm install --loglevel=error
      - REACT_APP_API_URL=$REACT_APP_API_URL SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Runt Unit Tests...
      - npm test